Public Class FileMapper

    Public Function GetFileMatch(Source As String, Dest As String)
        Dim RootPath As String = Text.RegularExpressions.Regex.Match(Source, "(?i)(.+?)(?=\\meshes)").Value
        Dim BSAPath As String = Source.Replace(RootPath, "")
        For i = 0 To SourceList.Count - 1
            If BSAPath = SourceList(i) Then Return Dest & NewList(i)
        Next
        Return Nothing
    End Function

    Dim SourceList As String() = {
        "\meshes\armor\1950stylecasual01\f\doa.nif",
        "\meshes\armor\1950stylecasual02\doa.nif",
        "\meshes\armor\1950stylesuit\f\doa.nif",
        "\meshes\armor\caesar\doa.nif",
        "\meshes\armor\cass\doa.nif",
        "\meshes\armor\centurion\doa.nif",
        "\meshes\armor\combatarmor\f\outfitf.doa.nif",
        "\meshes\armor\doctorli\f\outfitf.doa.nif",
        "\meshes\armor\greatkhans\v1.nif",
        "\meshes\armor\greatkhans\v2.nif",
        "\meshes\armor\greatkhans\v3.nif",
        "\meshes\armor\greatkhans\v4.nif",
        "\meshes\armor\leatherarmor\f\doa.nif",
        "\meshes\armor\leatherarmor\f\doa ref.nif",
        "\meshes\armor\legion\doa.explorer.nif",
        "\meshes\armor\legion\doa.pretorian.nif",
        "\meshes\armor\legion\doa.prime.nif",
        "\meshes\armor\legion\doa.recruit.nif",
        "\meshes\armor\legion\doa.veteran.nif",
        "\meshes\armor\legion\doa.vexillarius.nif",
        "\meshes\armor\lingerie\doa.nif",
        "\meshes\armor\lucassimms\f\doa.nif",
        "\meshes\armor\ncr_gambler\01.nif",
        "\meshes\armor\ncr_gambler\02.nif",
        "\meshes\armor\ncr_gambler\03.nif",
        "\meshes\armor\ncr_gambler\04.nif",
        "\meshes\armor\ncr_gambler\doa.nif",
        "\meshes\armor\prostitutes\01.nif",
        "\meshes\armor\prostitutes\02.nif",
        "\meshes\armor\prostitutes\03.nif",
        "\meshes\armor\raiderarmor01\f\doa.nif",
        "\meshes\armor\raiderarmor02\doa.nif",
        "\meshes\armor\raiderarmor03\doa.nif",
        "\meshes\armor\raiderarmor04\doa.nif",
        "\meshes\armor\republicans\01.nif",
        "\meshes\armor\republicans\02.nif",
        "\meshes\armor\republicans\03.nif",
        "\meshes\armor\republicans\04.nif",
        "\meshes\armor\robcojumpsuit\doa.nif",
        "\meshes\armor\slaverags\01.nif",
        "\meshes\armor\slaverags\02.nif",
        "\meshes\armor\tuxedo\doa.nif",
        "\meshes\armor\vaultsuitutility\f\doa.nif",
        "\meshes\armor\vaultsuitutility\f\doadad.nif",
        "\meshes\armor\wastelandclothing01\doa.nif",
        "\meshes\armor\wastelandclothing02\doa.nif",
        "\meshes\armor\wastelandclothing03\doa.nif",
        "\meshes\armor\wastelandclothing04\doa.nif",
        "\meshes\armor\wastelandclothing05\doa.nif",
        "\meshes\armor\wastelandclothing06\doa.nif",
        "\meshes\armor\wastelanddoctor01\doa.nif",
        "\meshes\armor\wastelandsettler01\f\doa.nif",
        "\meshes\armor\wastelandsettler02\f\doa.nif",
        "\meshes\nvdlc01\armor\starlet\doa.nif",
        "\meshes\nvdlc02\armor\daniel\doa.nif",
        "\meshes\nvdlc02\armor\deadhorse\doa.nif",
        "\meshes\nvdlc02\armor\jgraham\doa.nif",
        "\meshes\nvdlc02\armor\sorrows\01.nif",
        "\meshes\nvdlc02\armor\sorrows\02.nif",
        "\meshes\nvdlc02\armor\sorrows\03.nif",
        "\meshes\nvdlc02\armor\whitelegs\01.nif",
        "\meshes\nvdlc02\armor\whitelegs\02.nif",
        "\meshes\nvdlc03\armor\nvdlc03patientgown\doa.nif",
        "\meshes\nvdlc04\armor\markedmen\doa legate.nif",
        "\meshes\nvdlc04\armor\markedmen\doa lg.nif",
        "\meshes\nvdlc04\armor\markedmen\doa ncr.nif",
        "\meshes\nvdlc04\armor\markedmen\doa ranger.nif",
        "\meshes\nvdlc04\armor\ulysses\doa 21.nif",
        "\meshes\nvdlc04\armor\ulysses\doa cl.nif",
        "\meshes\nvdlc04\armor\ulysses\doa ncr.nif",
        "\meshes\nvdlc04\armor\ulysses\doa oldworld.nif",
        "\meshes\nvdlcpre3\armor\preordleather\doa.nif"}

    Dim NewList As String() = {
        "\meshes\doa\armor\1950stylecasual01\f\outfitf.nif",
        "\meshes\doa\armor\1950stylecasual02\outfitf.nif",
        "\meshes\doa\armor\1950stylesuit\f\outfitf.nif",
        "\meshes\doa\armor\caesar\caesar_f.nif",
        "\meshes\doa\armor\cass\cass_companion.nif",
        "\meshes\doa\armor\centurion\centurion_f.nif",
        "\meshes\doa\armor\combatarmor\f\outfitf.nif",
        "\meshes\doa\armor\doctorli\f\outfitf.nif",
        "\meshes\doa\armor\greatkhans\greatkhan_v1.nif",
        "\meshes\doa\armor\greatkhans\greatkhan_v2.nif",
        "\meshes\doa\armor\greatkhans\greatkhan_v3.nif",
        "\meshes\doa\armor\greatkhans\greatkhan_v4.nif",
        "\meshes\doa\armor\leatherarmor\f\outfitf.nif",
        "\meshes\doa\armor\leatherarmor\f\mark2leather_f.nif",
        "\meshes\doa\armor\legion\legionexplorer_f.nif",
        "\meshes\doa\armor\legion\legionpretorian_f.nif",
        "\meshes\doa\armor\legion\legionprime_f.nif",
        "\meshes\doa\armor\legion\legionrecruit_f.nif",
        "\meshes\doa\armor\legion\legionveteran_f.nif",
        "\meshes\doa\armor\legion\legionvexillarius_f.nif",
        "\meshes\doa\armor\lingerie\outfitf.nif",
        "\meshes\doa\armor\lucassimms\f\outfitf.nif",
        "\meshes\doa\armor\ncr_gambler\ncr_gambler_f01.nif",
        "\meshes\doa\armor\ncr_gambler\ncr_gambler_f02.nif",
        "\meshes\doa\armor\ncr_gambler\ncr_gambler_f03.nif",
        "\meshes\doa\armor\ncr_gambler\ncr_gambler_f04.nif",
        "\meshes\doa\armor\ncr_gambler\ncr_ambassador_fdoa.nif",
        "\meshes\doa\armor\prostitutes\prosfemale01.nif",
        "\meshes\doa\armor\prostitutes\prosfemale02.nif",
        "\meshes\doa\armor\prostitutes\prosfemale03.nif",
        "\meshes\doa\armor\raiderarmor01\f\outfitf.nif",
        "\meshes\doa\armor\raiderarmor02\outfitf.nif",
        "\meshes\doa\armor\raiderarmor03\outfitf.nif",
        "\meshes\doa\armor\raiderarmor04\outfitf.nif",
        "\meshes\doa\armor\republicans\republicanf_01.nif",
        "\meshes\doa\armor\republicans\republicanf_02.nif",
        "\meshes\doa\armor\republicans\republicanf_03.nif",
        "\meshes\doa\armor\republicans\republicanf_04.nif",
        "\meshes\doa\armor\robcojumpsuit\outfitf.nif",
        "\meshes\doa\armor\slaverags\slaverags_f1.nif",
        "\meshes\doa\armor\slaverags\slaverags_f2.nif",
        "\meshes\doa\armor\tuxedo\tuxedo_f.nif",
        "\meshes\doa\armor\vaultsuitutility\f\outfitf.nif",
        "\meshes\doa\armor\vaultsuitutility\f\vaultsuitutilitydadf.nif",
        "\meshes\doa\armor\wastelandclothing01\outfitf.nif",
        "\meshes\doa\armor\wastelandclothing02\outfitf.nif",
        "\meshes\doa\armor\wastelandclothing03\outfitf.nif",
        "\meshes\doa\armor\wastelandclothing04\outfitf.nif",
        "\meshes\doa\armor\wastelandclothing05\outfitf.nif",
        "\meshes\doa\armor\wastelandclothing06\outfitf.nif",
        "\meshes\doa\armor\wastelanddoctor01\outfitf.nif",
        "\meshes\doa\armor\wastelandsettler01\f\outfitf.nif",
        "\meshes\doa\armor\wastelandsettler02\f\outfitf.nif",
        "\meshes\doa\nvdlc01\armor\starlet\nvdlc01starletdress.nif",
        "\meshes\doa\nvdlc02\armor\daniel\nvdlc01danieloutfit_f.nif",
        "\meshes\doa\nvdlc02\armor\deadhorse\nvdlc02deadhorsestalkingf.nif",
        "\meshes\doa\nvdlc02\armor\jgraham\jgraham_outfit_f.nif",
        "\meshes\doa\nvdlc02\armor\sorrows\nvdlc02sorrowsoutfit01_f.nif",
        "\meshes\doa\nvdlc02\armor\sorrows\nvdlc02sorrowsoutfit02_f.nif",
        "\meshes\doa\nvdlc02\armor\sorrows\nvdlc02wakingcloud_f.nif",
        "\meshes\doa\nvdlc02\armor\whitelegs\whitelegs_vf01.nif",
        "\meshes\doa\nvdlc02\armor\whitelegs\whitelegs_vf02.nif",
        "\meshes\doa\nvdlc03\armor\nvdlc03patientgown\nvdlc03patientgown_f.nif",
        "\meshes\doa\nvdlc04\armor\markedmen\markedmen_legate_f.nif",
        "\meshes\doa\nvdlc04\armor\markedmen\markedmen_lg_f.nif",
        "\meshes\doa\nvdlc04\armor\markedmen\markedmen_ncr_f.nif",
        "\meshes\doa\nvdlc04\armor\markedmen\markedmen_ranger_f.nif",
        "\meshes\doa\nvdlc04\armor\ulysses\ulysses_21_f.nif",
        "\meshes\doa\nvdlc04\armor\ulysses\ulysses_cl_f.nif",
        "\meshes\doa\nvdlc04\armor\ulysses\ulysses_ncr_f.nif",
        "\meshes\doa\nvdlc04\armor\ulysses\ulysses_oldworld_f.nif",
        "\meshes\doa\nvdlcpre3\armor\preordleather\preordleatherarmorf.nif"}

End Class
